- hosts: masters
  become: yes
  tasks:
  - name: Initialize the cluster
    shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> pod_initialize.log
    args:
      chdir: $HOME
      creates: pod_initialize.log
  
  - name: Create directory for kube config file
    become_user: ubuntu
    file:
      path: $HOME/.kube
      state: directory
      mode: '0755'

  - name: Copy the kube config to the created directory
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/ubuntu/.kube/config
      remote_src: yes
      owner: ubuntu

  - name: Install CNI for the cluster
    become_user: ubuntu
    shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.30.2/manifests/calico.yaml >> cni_setup.log
    args:
      chdir: $HOME
      creates: cni_setup.log