- hosts: masters
  become: yes
  tasks:
  - name: Get join command
    shell: kubeadm token create --print-join-command
    register: join_command_raw

  - name: Set join command
    set_fact:
      join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: yes
  tasks:
  - name: Wait for the master become reachable
    wait_for: "host={{ hostvars['master-node']['ansible_default_ipv4']['address'] }} port=6443 timeout=1"
  
  - name: Join cluster
    shell: "{{ hostvars['master-node'].join_command }} >> join_cluster.log"
    args:
      chdir: $HOME
      creates: join_cluster.log